### PR TITLE
added better styling

### PR DESCRIPTION
**Pull request by ghost**
added better styling for the **navbar** and the **burger menu and close menu**

and formatted some files

### CODE REVIEW

**Comment by rockwillck** [comment]
Thank you for the PR! Unfortunately, this seems to be more of a custom theme than a change to Lenoir, and because the reformatting changes almost every line, it's very hard to tell what changes were made. Could you elaborate on what exactly changed? It may be possible to turn your changes into a new built-in theme.

**Comment by ghost** [comment]
hey @rockwillck... thanks for the reply

this code that i have commited is not really that different from the original it just looks like it because of the formatting...

the main content changed is

```js
        foldButton.className = "foldButton"
        foldButton.innerText = "×"
        this.nav.appendChild(foldButton)
        let openButton = document.createElement("button")
        openButton.className = "openButton"
        openButton.innerText = "☰"
        doc.appendChild(openButton)
```

to

```js
    foldButton.className = "foldButton";
    let closeButton1 = document.createElement("button");
    let closeButton2 = document.createElement("button");
    closeButton1.className = "closeButton1";
    closeButton2.className = "closeButton2";
    foldButton.replaceChildren(closeButton1, closeButton2);
    this.nav.appendChild(foldButton);
    let openButton = document.createElement("button");
    let innerBurgerMenu = document.createElement("div");
    // add 3 div between
    let burgerLine = document.createElement("div");
    burgerLine.className = "burgerLine";
    innerBurgerMenu.replaceChildren(
      burgerLine.cloneNode(),
      burgerLine.cloneNode(),
      burgerLine,
    );
    openButton.className = "openButton";
    openButton.replaceChildren(innerBurgerMenu);
```

and in theme.css file

```css
.openButton {
    background-color: transparent;
    filter: drop-shadow(0 0 1px rgba(0, 0, 0, 1));
    display: flex;
    justify-content: center;
    align-items: center;
    border: none;
    top: 10px;
    left: 10px;
    color: white;
  }

  .burgerLine {
    width: 28px;
    height: 2px;
    background-color: white;
    margin: 5px;
  }

  .closeButton1 {
    margin-top: 30px;
    border: none;
    font-weight: bold;
    position: absolute;
    right: 10px;
    color: white;
    height: 1px;
    width: 15px;
    transform: rotate(45deg);
  }

  .closeButton2 {
    border: none;
    margin-top: 30px;
    font-weight: bold;
    position: absolute;
    right: 10px;
    color: white;
    height: 1px;
    width: 15px;
    transform: rotate(-45deg);
  }
```

**Comment by ghost** [comment]
all of this code is to remove the bad navbar icons of closing and opening the sidebar...

with the replacing of `openButton.innerText = "☰"` and `foldButton.innerText = "×"`

with div's with their own styling
Screenshot 2024-06-01 192531
Screenshot 2024-06-01 192537

**Comment by rockwillck** [comment]
Ah, I see. That could be a smart change, I'll look into it - the only reason I really hesitate is that this change clutters up the document tree a little. Maybe something with SVG?

**Pull request closed without merging**
